name: Build and Push to Artifact Registry

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'
env:
  PROJECT_ID: field-engineering-apac
  REGION: australia-southeast1
  REPO: australia-southeast1-docker.pkg.dev/field-engineering-apac/public-repo

jobs:
  build-push-artifact:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: "actions/checkout@v3"

      - id: "auth"
        uses: "google-github-actions/auth@v1"
        with:
          credentials_json: "${{ secrets.SERVICE_ACCOUNT_KEY }}"

      - name: "Set up Cloud SDK"
        uses: "google-github-actions/setup-gcloud@v1"

      - name: "Use gcloud CLI"
        run: "gcloud info"

      - name: "Docker auth"
        run: |-
          gcloud auth configure-docker ${{ env.REGION }}-docker.pkg.dev --quiet

      - name: Build and push image
        run: PUSH_MULTIARCH=true make docker-build